title: Changho Shin
author: Changho Shin
face: /assets/img/chshin.jpg
description: Postdoc at Princeton University
email: cs1095@princeton.edu
github: https://github.com/ch-shin
google_scholar: https://scholar.google.com/citations?user=mF95I24AAAAJ&hl=en&oi=ao
linkedin: https://www.linkedin.com/in/changho-shin/
cv: https://ch-shin.github.io/assets/cv/cv_chshin.pdf
twitter: https://twitter.com/Changho_Shin_
theme: jekyll-theme-minimal

header_pages:
  - index.md
  # - thoughts.md
